---
- name: Selenoid | Install certain python modules for docker
  pip:
    name: "{{ item.name }}"
  with_items:
  - { name: docker-py }

- name: Selenoid | Check selenoid container exist
  shell: 'docker ps -aq --filter "name={{ item }}"'
  with_items:
    - 'selenoid'
  register: found_containers

- name: Selenoid | Remove selenoid container if exist
  shell: 'docker stop {{ item.item }} && docker rm -fv {{ item.item }}'
  with_items: '{{ found_containers.results }}'
  when: item.stdout

- name: Selenoid | Run CM container, download browser images and run selenoid
  docker_container:
    name: cm
    image: "aerokube/cm:{{ selenoid_cm_version }}"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/root:/root"
    env:
      TZ: "{{ selenoid_time_zone }}"
      OVERRIDE_HOME: "/root"
      DOCKER_API_VERSION: "{{ selenoid_docker_api_version }}"
    command: >
      selenoid start
        --config-dir {{ selenoid_config_dir }}
        --version {{ selenoid_version }}
        --tmpfs {{ selenoid_tmpfs }}
        --env DOCKER_API_VERSION={{ selenoid_docker_api_version }}
        --browsers firefox,opera,chrome
        --last-versions 5
        --force
        --args "-limit {{ selenoid_limit }} -listen :{{ selenoid_listen_port }} -conf {{ selenoid_config_dir }}/browsers.json"
